### ISSUE TITLE
Rerendering a theme does not use new variables from config.yaml

### ISSUE THREAD

**Issue by magnetotail** [s-ol/themer#63] opened 2017-11-03 14:18 UTC
When I tried to add new variables for fonts for different applications these did not get used after "themer render all". The placeholders were just left empty. When I generated a new theme I noticed, that my new variables suddenly appeared in the colors.yaml of the new theme. It seems that themer does not update the colors.yaml with new variables when these get added. Therefore it is not possible to add new variables by simply putting them in the config.yaml.

**Comment by s-ol** [comment] 2017-11-07 16:34
Right now this is "expected behaviour"; rerendering a theme means re-rendering the template using the *resolved* variables, including the ones from the config.
However it is clear why you would rather have it work the way you describe it.

In the end it boils down more or less to #24, although that issue as it is described in the comments is a bit too vague/thought too big.

**Comment by s-ol** [comment] 2018-09-19 09:39
closing: working as intended. comments on future design in #24

**Closed as completed by s-ol** 2018-09-19 09:39 UTC

**Comment by ghost** [comment] 2018-12-28 01:35
This bit me extremely hard when I moved my templates and themes to a new system - one with a much higher resolution screen. Suddenly, I had to manually re-generate new themes to account for a number of differences.

I added `context = munge_context(context, config['variables'] )` at the end of `render()` just before the `render_templates()` call, which solved my problem nicely - just a quick hack to solve this particular problem for me, since I happen to always want the current value of the config, and am mostly concerned about the colors.

Since you already covered this here, I won't open a pull request, but if anyone else wants the behavior of using the current variable definitions, rather than the ones from the time the theme was generated, see https://github.com/mach327/themer/tree/render_with_new_context

@s-ol Thanks for the awesome software!
